//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 12:26:49 PM IST 
//


package com.attunedlabs.scheduler.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="startAt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="endAt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateFormat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="day_of_Week" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://attunedlabs.com/internalevents/Scheduler}repeatInterval"/>
 *         &lt;element name="lastday" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="excludeHolidays" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timezone",
    "startAt",
    "endAt",
    "dateFormat",
    "dayOfWeek",
    "duration",
    "repeatInterval",
    "lastday",
    "excludeHolidays"
})
public class CronExp
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String timezone;
    protected String startAt;
    protected String endAt;
    protected String dateFormat;
    @XmlElement(name = "day_of_Week")
    protected String dayOfWeek;
    protected String duration;
    @XmlElement(namespace = "http://attunedlabs.com/internalevents/Scheduler", required = true)
    protected RepeatInterval repeatInterval;
    protected String lastday;
    protected String excludeHolidays;

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimezone(String value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the startAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartAt() {
        return startAt;
    }

    /**
     * Sets the value of the startAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartAt(String value) {
        this.startAt = value;
    }

    /**
     * Gets the value of the endAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndAt() {
        return endAt;
    }

    /**
     * Sets the value of the endAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndAt(String value) {
        this.endAt = value;
    }

    /**
     * Gets the value of the dateFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFormat() {
        return dateFormat;
    }

    /**
     * Sets the value of the dateFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFormat(String value) {
        this.dateFormat = value;
    }

    /**
     * Gets the value of the dayOfWeek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * Sets the value of the dayOfWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayOfWeek(String value) {
        this.dayOfWeek = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the repeatInterval property.
     * 
     * @return
     *     possible object is
     *     {@link RepeatInterval }
     *     
     */
    public RepeatInterval getRepeatInterval() {
        return repeatInterval;
    }

    /**
     * Sets the value of the repeatInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepeatInterval }
     *     
     */
    public void setRepeatInterval(RepeatInterval value) {
        this.repeatInterval = value;
    }

    /**
     * Gets the value of the lastday property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastday() {
        return lastday;
    }

    /**
     * Sets the value of the lastday property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastday(String value) {
        this.lastday = value;
    }

    /**
     * Gets the value of the excludeHolidays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcludeHolidays() {
        return excludeHolidays;
    }

    /**
     * Sets the value of the excludeHolidays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcludeHolidays(String value) {
        this.excludeHolidays = value;
    }

}
