//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 12:26:49 PM IST 
//


package com.attunedlabs.scheduler.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isEnabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="featureInfo">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="featureName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="featureGroup" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="jobservice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jobGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SchedulingExpresssion">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="timerExp" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="startAt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="endAt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="dateFormat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element ref="{http://attunedlabs.com/internalevents/Scheduler}repeatInterval"/>
 *                             &lt;element name="delayduration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="repeatCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="repeatForever" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="excludeHolidays" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="cronExp" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="startAt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="endAt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="dateFormat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="day_of_Week" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element ref="{http://attunedlabs.com/internalevents/Scheduler}repeatInterval"/>
 *                             &lt;element name="lastday" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="excludeHolidays" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="JobContextData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddedByUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "isEnabled",
    "featureInfo",
    "jobservice",
    "jobGroup",
    "schedulingExpresssion",
    "jobContextData",
    "addedByUser"
})
public class ScheduledJobConfiguration
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(required = true)
    protected boolean isEnabled;
    @XmlElement(required = true)
    protected FeatureInfo featureInfo;
    @XmlElement(required = true)
    protected String jobservice;
    @XmlElement(required = true)
    protected String jobGroup;
    @XmlElement(name = "SchedulingExpresssion", required = true)
    protected SchedulingExpresssion schedulingExpresssion;
    @XmlElement(name = "JobContextData")
    protected String jobContextData;
    @XmlElement(name = "AddedByUser")
    protected String addedByUser;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * Sets the value of the isEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEnabled(boolean value) {
        this.isEnabled = value;
    }

    /**
     * Gets the value of the featureInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureInfo }
     *     
     */
    public FeatureInfo getFeatureInfo() {
        return featureInfo;
    }

    /**
     * Sets the value of the featureInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureInfo }
     *     
     */
    public void setFeatureInfo(FeatureInfo value) {
        this.featureInfo = value;
    }

    /**
     * Gets the value of the jobservice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobservice() {
        return jobservice;
    }

    /**
     * Sets the value of the jobservice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobservice(String value) {
        this.jobservice = value;
    }

    /**
     * Gets the value of the jobGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * Sets the value of the jobGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobGroup(String value) {
        this.jobGroup = value;
    }

    /**
     * Gets the value of the schedulingExpresssion property.
     * 
     * @return
     *     possible object is
     *     {@link SchedulingExpresssion }
     *     
     */
    public SchedulingExpresssion getSchedulingExpresssion() {
        return schedulingExpresssion;
    }

    /**
     * Sets the value of the schedulingExpresssion property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchedulingExpresssion }
     *     
     */
    public void setSchedulingExpresssion(SchedulingExpresssion value) {
        this.schedulingExpresssion = value;
    }

    /**
     * Gets the value of the jobContextData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobContextData() {
        return jobContextData;
    }

    /**
     * Sets the value of the jobContextData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobContextData(String value) {
        this.jobContextData = value;
    }

    /**
     * Gets the value of the addedByUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddedByUser() {
        return addedByUser;
    }

    /**
     * Sets the value of the addedByUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddedByUser(String value) {
        this.addedByUser = value;
    }

}
