//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.17 at 03:07:52 PM IST 
//


package com.attunedlabs.featuremetainfo.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="partitionFunction" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fileGroup" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="fileGroupName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="location" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="size" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="maxSize" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="fileGrowth" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="columnType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="rangeType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="values" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "partitionFunction"
})
public class PartitionSchema
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected PartitionFunction partitionFunction;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the partitionFunction property.
     * 
     * @return
     *     possible object is
     *     {@link PartitionFunction }
     *     
     */
    public PartitionFunction getPartitionFunction() {
        return partitionFunction;
    }

    /**
     * Sets the value of the partitionFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartitionFunction }
     *     
     */
    public void setPartitionFunction(PartitionFunction value) {
        this.partitionFunction = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
