//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.01 at 04:07:19 PM IST 
//


package com.attunedlabs.permastore.config.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EventName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PermaStoreEventHandler" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="onEvent" use="required" type="{}event" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eventName",
    "permaStoreEventHandler"
})
public class PermaStoreEvent
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EventName", required = true)
    protected String eventName;
    @XmlElement(name = "PermaStoreEventHandler")
    protected String permaStoreEventHandler;
    @XmlAttribute(name = "onEvent", required = true)
    protected Event onEvent;

    /**
     * Gets the value of the eventName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * Sets the value of the eventName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventName(String value) {
        this.eventName = value;
    }

    /**
     * Gets the value of the permaStoreEventHandler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermaStoreEventHandler() {
        return permaStoreEventHandler;
    }

    /**
     * Sets the value of the permaStoreEventHandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermaStoreEventHandler(String value) {
        this.permaStoreEventHandler = value;
    }

    /**
     * Gets the value of the onEvent property.
     * 
     * @return
     *     possible object is
     *     {@link Event }
     *     
     */
    public Event getOnEvent() {
        return onEvent;
    }

    /**
     * Sets the value of the onEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Event }
     *     
     */
    public void setOnEvent(Event value) {
        this.onEvent = value;
    }

}
