//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.26 at 03:03:13 PM IST 
//


package com.getusroi.featuremetainfo.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.getusroi.featuremetainfo.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.getusroi.featuremetainfo.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FeatureMetainfo }
     * 
     */
    public FeatureMetainfo createFeatureMetainfo() {
        return new FeatureMetainfo();
    }

    /**
     * Create an instance of {@link FeatureGroup }
     * 
     */
    public FeatureGroup createFeatureGroup() {
        return new FeatureGroup();
    }

    /**
     * Create an instance of {@link PermaStoreConfigurations }
     * 
     */
    public PermaStoreConfigurations createPermaStoreConfigurations() {
        return new PermaStoreConfigurations();
    }

    /**
     * Create an instance of {@link PermaStoreConfiguration }
     * 
     */
    public PermaStoreConfiguration createPermaStoreConfiguration() {
        return new PermaStoreConfiguration();
    }

    /**
     * Create an instance of {@link PolicyConfigurations }
     * 
     */
    public PolicyConfigurations createPolicyConfigurations() {
        return new PolicyConfigurations();
    }

    /**
     * Create an instance of {@link PolicyConfiguration }
     * 
     */
    public PolicyConfiguration createPolicyConfiguration() {
        return new PolicyConfiguration();
    }

    /**
     * Create an instance of {@link EventResources }
     * 
     */
    public EventResources createEventResources() {
        return new EventResources();
    }

    /**
     * Create an instance of {@link EventResource }
     * 
     */
    public EventResource createEventResource() {
        return new EventResource();
    }

    /**
     * Create an instance of {@link DynaStoreConfigurations }
     * 
     */
    public DynaStoreConfigurations createDynaStoreConfigurations() {
        return new DynaStoreConfigurations();
    }

    /**
     * Create an instance of {@link DynaStoreConfiguration }
     * 
     */
    public DynaStoreConfiguration createDynaStoreConfiguration() {
        return new DynaStoreConfiguration();
    }

    /**
     * Create an instance of {@link Features }
     * 
     */
    public Features createFeatures() {
        return new Features();
    }

    /**
     * Create an instance of {@link Feature }
     * 
     */
    public Feature createFeature() {
        return new Feature();
    }

    /**
     * Create an instance of {@link FeatureImplementations }
     * 
     */
    public FeatureImplementations createFeatureImplementations() {
        return new FeatureImplementations();
    }

    /**
     * Create an instance of {@link FeatureDataContexts }
     * 
     */
    public FeatureDataContexts createFeatureDataContexts() {
        return new FeatureDataContexts();
    }

    /**
     * Create an instance of {@link IntegrationPipeLineConfigurations }
     * 
     */
    public IntegrationPipeLineConfigurations createIntegrationPipeLineConfigurations() {
        return new IntegrationPipeLineConfigurations();
    }

    /**
     * Create an instance of {@link StaticFileConfiguration }
     * 
     */
    public StaticFileConfiguration createStaticFileConfiguration() {
        return new StaticFileConfiguration();
    }

    /**
     * Create an instance of {@link DBConfiguration }
     * 
     */
    public DBConfiguration createDBConfiguration() {
        return new DBConfiguration();
    }

    /**
     * Create an instance of {@link Database }
     * 
     */
    public Database createDatabase() {
        return new Database();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link ConfigFile }
     * 
     */
    public ConfigFile createConfigFile() {
        return new ConfigFile();
    }

    /**
     * Create an instance of {@link PipeConfiguration }
     * 
     */
    public PipeConfiguration createPipeConfiguration() {
        return new PipeConfiguration();
    }

    /**
     * Create an instance of {@link DataContexts }
     * 
     */
    public DataContexts createDataContexts() {
        return new DataContexts();
    }

    /**
     * Create an instance of {@link FeatureImplementation }
     * 
     */
    public FeatureImplementation createFeatureImplementation() {
        return new FeatureImplementation();
    }

}
