//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 12:39:14 PM IST 
//


package com.attunedlabs.dynastore.config.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="onReload" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="onTermination" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="onEntryAdded" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="onEntryDeleted" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="onEntryUpdated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "onReload",
    "onTermination",
    "onEntryAdded",
    "onEntryDeleted",
    "onEntryUpdated"
})
public class PublishEvent
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String onReload;
    protected String onTermination;
    protected String onEntryAdded;
    protected String onEntryDeleted;
    protected String onEntryUpdated;

    /**
     * Gets the value of the onReload property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnReload() {
        return onReload;
    }

    /**
     * Sets the value of the onReload property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnReload(String value) {
        this.onReload = value;
    }

    /**
     * Gets the value of the onTermination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnTermination() {
        return onTermination;
    }

    /**
     * Sets the value of the onTermination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnTermination(String value) {
        this.onTermination = value;
    }

    /**
     * Gets the value of the onEntryAdded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnEntryAdded() {
        return onEntryAdded;
    }

    /**
     * Sets the value of the onEntryAdded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnEntryAdded(String value) {
        this.onEntryAdded = value;
    }

    /**
     * Gets the value of the onEntryDeleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnEntryDeleted() {
        return onEntryDeleted;
    }

    /**
     * Sets the value of the onEntryDeleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnEntryDeleted(String value) {
        this.onEntryDeleted = value;
    }

    /**
     * Gets the value of the onEntryUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnEntryUpdated() {
        return onEntryUpdated;
    }

    /**
     * Sets the value of the onEntryUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnEntryUpdated(String value) {
        this.onEntryUpdated = value;
    }

}
