USE roi;

insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (22,'gap',0,1,0,'This is gap tenant','tenant',1,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (23,'site1',0,1,22,'This is  sit1 Site','site',2,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (25,'featuregroup1',0,1,23,'This is  featureGroup1 Feature Group','feature_group',3,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (26,'feature1',0,1,25,'This is  feature1 Feature','feature',4,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (28,'label',0,1,23,'This is  featureGroup2 Feature Group','feature_group',3,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (241,'Parcel',0,1,25,'This is parcel feature','feature',4,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (324,'labelservice',0,1,28,'This is  feature1 Feature','feature',4,'1.0',855);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (571,'print',0,1,23,'This is print featuregroup','feature_group',3,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (572,'printservice',0,1,571,'This is printservice feature ','feature',4,'1.0',857);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (689,'nicelabel',0,1,23,'This is nicelabel featureGroup','feature_group',3,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (690,'nicelabelservice',0,0,689,'This is nicelabelservice featurename','feature',4,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (720,'bartender',0,1,23,'bartender Feature Group ','feature_group',3,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (721,'bartenderservice',0,0,720,'bartender Feature ','feature',4,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (740,'parcel',0,1,23,'This is site1 parcel','feature_group',3,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (741,'parcelservice',0,1,740,'This is parcel parcelservice','feature',4,'1.0',882);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (762,'test',0,1,23,'testing','feature_group',3,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (763,'testService',0,1,762,'testingservices','feature',4,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (855,'roi',0,0,324,'This is roi vendor','vendor',5,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (856,'nicelabel',0,0,324,'This is nicelabel vendor','vendor',5,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (857,'printnode',0,0,572,'This is printnode vendor','vendor',5,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (858,'cups',0,0,572,'This is cups vendor','vendor',5,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (859,'bartender',0,0,324,'This is bartender vendor','vendor',5,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (860,'testvendor',0,0,763,'This is testvendor vendor','vendor',5,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (861,'feature1vendor',0,1,26,'This is feature1vendor tenant','vendor',5,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (862,'testParcelVendor',0,1,241,'This is tetParcelVendor tenant','vendor',5,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (863,'Test-Tenant',0,0,0,'Test Node at Levek-1','tenant',1,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (866,'Test-Tenant',0,0,0,'Test Node at Levek-1','tenant',1,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (882,'roi',0,0,741,'This is roi-parcel vendor','vendor',5,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (883,'connectShip',0,0,741,'This is connectShip-parcel vendor','vendor',5,'1.0',0);
insert into `confignode`(`nodeId`,`nodeName`,`isRoot`,`hasChildren`,`parentNodeId`,`description`,`type`,`level`,`version`,`primaryFeatureId`) values (884,'testParcelVendor',0,0,241,'This is testParcelVendor 1.1 vendor','vendor',5,'1.1',0);

insert into `AreaList`(`AreaId`,`AreaType`,`AreaName`) values (1,'Stage','STA1');
insert into `AreaList`(`AreaId`,`AreaType`,`AreaName`) values (2,'Stage','STA2');
insert into `AreaList`(`AreaId`,`AreaType`,`AreaName`) values (3,'PIC','PIC1');
insert into `AreaList`(`AreaId`,`AreaType`,`AreaName`) values (4,'PIC','PIC2');
insert into `AreaList`(`AreaId`,`AreaType`,`AreaName`) values (1,'Stage','STA1');
insert into `AreaList`(`AreaId`,`AreaType`,`AreaName`) values (2,'Stage','STA2');
insert into `AreaList`(`AreaId`,`AreaType`,`AreaName`) values (3,'PIC','PIC1');
insert into `AreaList`(`AreaId`,`AreaType`,`AreaName`) values (4,'PIC','PIC2');

insert into `featureMaster`(`masterNodeId`,`featureName`,`featureGroup`,`siteId`,`version`,`description`,`multiVendorSupport`,`product`) values (1,'Parcel','featuregroup1',23,'V_1','Test FeatureMaster ',1,'wms2.0');
insert into `featureMaster`(`masterNodeId`,`featureName`,`featureGroup`,`siteId`,`version`,`description`,`multiVendorSupport`,`product`) values (2,'labelservice','label',23,'V_1','Test FeatureMaster ',1,'wms2.0');
insert into `featureMaster`(`masterNodeId`,`featureName`,`featureGroup`,`siteId`,`version`,`description`,`multiVendorSupport`,`product`) values (3,'printservice','print',23,'V_1','print service data',1,'wms2.0');
insert into `featureMaster`(`masterNodeId`,`featureName`,`featureGroup`,`siteId`,`version`,`description`,`multiVendorSupport`,`product`) values (4,'nicelabelservice','nicelabel',23,'V_1','nicelabelservice data',1,'wms2.0');
insert into `featureMaster`(`masterNodeId`,`featureName`,`featureGroup`,`siteId`,`version`,`description`,`multiVendorSupport`,`product`) values (5,'bartenderservice','bartender',23,'V_1','test ',1,'wms2.0');
insert into `featureMaster`(`masterNodeId`,`featureName`,`featureGroup`,`siteId`,`version`,`description`,`multiVendorSupport`,`product`) values (7,'parcelservice','parcel',23,'V_1','Test',1,'wms2.0');
insert into `featureMaster`(`masterNodeId`,`featureName`,`featureGroup`,`siteId`,`version`,`description`,`multiVendorSupport`,`product`) values (8,'testService','test',23,'V_1','testing',1,'wms2.0');