//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.19 at 05:01:20 PM IST 
//


package com.attunedlabs.integrationfwk.config.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://attunedlabs.com/internal/pipeline}Pipeline" minOccurs="0"/>
 *         &lt;element ref="{http://attunedlabs.com/internal/integration-fwk-Supporting}InnerIfBlock" minOccurs="0"/>
 *         &lt;element ref="{http://attunedlabs.com/internal/integration-fwk-Supporting}InnerElseIfBlock" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://attunedlabs.com/internal/integration-fwk-Supporting}InnerElseBlock" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pipeline",
    "innerIfBlock",
    "innerElseIfBlock",
    "innerElseBlock"
})
public class ElseBlock
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Pipeline", namespace = "http://attunedlabs.com/internal/pipeline")
    protected Pipeline pipeline;
    @XmlElement(name = "InnerIfBlock", namespace = "http://attunedlabs.com/internal/integration-fwk-Supporting")
    protected InnerIfBlock innerIfBlock;
    @XmlElement(name = "InnerElseIfBlock", namespace = "http://attunedlabs.com/internal/integration-fwk-Supporting")
    protected List<InnerElseIfBlock> innerElseIfBlock;
    @XmlElement(name = "InnerElseBlock", namespace = "http://attunedlabs.com/internal/integration-fwk-Supporting")
    protected InnerElseBlock innerElseBlock;

    /**
     * Gets the value of the pipeline property.
     * 
     * @return
     *     possible object is
     *     {@link Pipeline }
     *     
     */
    public Pipeline getPipeline() {
        return pipeline;
    }

    /**
     * Sets the value of the pipeline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pipeline }
     *     
     */
    public void setPipeline(Pipeline value) {
        this.pipeline = value;
    }

    /**
     * Gets the value of the innerIfBlock property.
     * 
     * @return
     *     possible object is
     *     {@link InnerIfBlock }
     *     
     */
    public InnerIfBlock getInnerIfBlock() {
        return innerIfBlock;
    }

    /**
     * Sets the value of the innerIfBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link InnerIfBlock }
     *     
     */
    public void setInnerIfBlock(InnerIfBlock value) {
        this.innerIfBlock = value;
    }

    /**
     * Gets the value of the innerElseIfBlock property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the innerElseIfBlock property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInnerElseIfBlock().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InnerElseIfBlock }
     * 
     * 
     */
    public List<InnerElseIfBlock> getInnerElseIfBlock() {
        if (innerElseIfBlock == null) {
            innerElseIfBlock = new ArrayList<InnerElseIfBlock>();
        }
        return this.innerElseIfBlock;
    }

    /**
     * Gets the value of the innerElseBlock property.
     * 
     * @return
     *     possible object is
     *     {@link InnerElseBlock }
     *     
     */
    public InnerElseBlock getInnerElseBlock() {
        return innerElseBlock;
    }

    /**
     * Sets the value of the innerElseBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link InnerElseBlock }
     *     
     */
    public void setInnerElseBlock(InnerElseBlock value) {
        this.innerElseBlock = value;
    }

}
