//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.19 at 05:01:20 PM IST 
//


package com.attunedlabs.integrationfwk.config.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LoopingCondition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://attunedlabs.com/internal/pipeline}Pipeline"/>
 *       &lt;/sequence>
 *       &lt;attribute name="parallelProcessing" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "loopingCondition",
    "pipeline"
})
public class LoopActivity
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "LoopingCondition", required = true)
    protected String loopingCondition;
    @XmlElement(name = "Pipeline", namespace = "http://attunedlabs.com/internal/pipeline", required = true)
    protected Pipeline pipeline;
    @XmlAttribute(name = "parallelProcessing")
    protected Boolean parallelProcessing;

    /**
     * Gets the value of the loopingCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoopingCondition() {
        return loopingCondition;
    }

    /**
     * Sets the value of the loopingCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoopingCondition(String value) {
        this.loopingCondition = value;
    }

    /**
     * Gets the value of the pipeline property.
     * 
     * @return
     *     possible object is
     *     {@link Pipeline }
     *     
     */
    public Pipeline getPipeline() {
        return pipeline;
    }

    /**
     * Sets the value of the pipeline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pipeline }
     *     
     */
    public void setPipeline(Pipeline value) {
        this.pipeline = value;
    }

    /**
     * Gets the value of the parallelProcessing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isParallelProcessing() {
        if (parallelProcessing == null) {
            return false;
        } else {
            return parallelProcessing;
        }
    }

    /**
     * Sets the value of the parallelProcessing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setParallelProcessing(Boolean value) {
        this.parallelProcessing = value;
    }

}
