//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.19 at 05:01:20 PM IST 
//


package com.attunedlabs.integrationfwk.config.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MailAttachment">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="mailAttachmentXpath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="mailAttachmentNameXpath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="mailAttachmentFormatXpath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mailAttachment"
})
public class MailAttachments
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "MailAttachment", required = true)
    protected MailAttachment mailAttachment;

    /**
     * Gets the value of the mailAttachment property.
     * 
     * @return
     *     possible object is
     *     {@link MailAttachment }
     *     
     */
    public MailAttachment getMailAttachment() {
        return mailAttachment;
    }

    /**
     * Sets the value of the mailAttachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link MailAttachment }
     *     
     */
    public void setMailAttachment(MailAttachment value) {
        this.mailAttachment = value;
    }

}
