//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.19 at 05:01:20 PM IST 
//


package com.attunedlabs.integrationfwk.config.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.attunedlabs.integrationfwk.config.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.attunedlabs.integrationfwk.config.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pipeline }
     * 
     */
    public Pipeline createPipeline() {
        return new Pipeline();
    }

    /**
     * Create an instance of {@link Drop }
     * 
     */
    public Drop createDrop() {
        return new Drop();
    }

    /**
     * Create an instance of {@link InnerIfBlock }
     * 
     */
    public InnerIfBlock createInnerIfBlock() {
        return new InnerIfBlock();
    }

    /**
     * Create an instance of {@link InnerElseBlock }
     * 
     */
    public InnerElseBlock createInnerElseBlock() {
        return new InnerElseBlock();
    }

    /**
     * Create an instance of {@link InnerElseIfBlock }
     * 
     */
    public InnerElseIfBlock createInnerElseIfBlock() {
        return new InnerElseIfBlock();
    }

    /**
     * Create an instance of {@link FilterResponse }
     * 
     */
    public FilterResponse createFilterResponse() {
        return new FilterResponse();
    }

    /**
     * Create an instance of {@link Send }
     * 
     */
    public Send createSend() {
        return new Send();
    }

    /**
     * Create an instance of {@link IntegrationPipes }
     * 
     */
    public IntegrationPipes createIntegrationPipes() {
        return new IntegrationPipes();
    }

    /**
     * Create an instance of {@link IntegrationPipe }
     * 
     */
    public IntegrationPipe createIntegrationPipe() {
        return new IntegrationPipe();
    }

    /**
     * Create an instance of {@link PipeActivity }
     * 
     */
    public PipeActivity createPipeActivity() {
        return new PipeActivity();
    }

    /**
     * Create an instance of {@link XSLTEnricherActivity }
     * 
     */
    public XSLTEnricherActivity createXSLTEnricherActivity() {
        return new XSLTEnricherActivity();
    }

    /**
     * Create an instance of {@link FTLEnricherActivity }
     * 
     */
    public FTLEnricherActivity createFTLEnricherActivity() {
        return new FTLEnricherActivity();
    }

    /**
     * Create an instance of {@link JDBCIntActivity }
     * 
     */
    public JDBCIntActivity createJDBCIntActivity() {
        return new JDBCIntActivity();
    }

    /**
     * Create an instance of {@link EmailNotifyActivity }
     * 
     */
    public EmailNotifyActivity createEmailNotifyActivity() {
        return new EmailNotifyActivity();
    }

    /**
     * Create an instance of {@link FilterPipelineActivity }
     * 
     */
    public FilterPipelineActivity createFilterPipelineActivity() {
        return new FilterPipelineActivity();
    }

    /**
     * Create an instance of {@link CamelRouteEndPoint }
     * 
     */
    public CamelRouteEndPoint createCamelRouteEndPoint() {
        return new CamelRouteEndPoint();
    }

    /**
     * Create an instance of {@link PropertiesActivity }
     * 
     */
    public PropertiesActivity createPropertiesActivity() {
        return new PropertiesActivity();
    }

    /**
     * Create an instance of {@link EventPublishActivity }
     * 
     */
    public EventPublishActivity createEventPublishActivity() {
        return new EventPublishActivity();
    }

    /**
     * Create an instance of {@link GroovyScriptActivity }
     * 
     */
    public GroovyScriptActivity createGroovyScriptActivity() {
        return new GroovyScriptActivity();
    }

    /**
     * Create an instance of {@link ConditionalFlowActivity }
     * 
     */
    public ConditionalFlowActivity createConditionalFlowActivity() {
        return new ConditionalFlowActivity();
    }

    /**
     * Create an instance of {@link LoopActivity }
     * 
     */
    public LoopActivity createLoopActivity() {
        return new LoopActivity();
    }

    /**
     * Create an instance of {@link ConditionalFlow }
     * 
     */
    public ConditionalFlow createConditionalFlow() {
        return new ConditionalFlow();
    }

    /**
     * Create an instance of {@link IfBlock }
     * 
     */
    public IfBlock createIfBlock() {
        return new IfBlock();
    }

    /**
     * Create an instance of {@link ElseIfBlock }
     * 
     */
    public ElseIfBlock createElseIfBlock() {
        return new ElseIfBlock();
    }

    /**
     * Create an instance of {@link ElseBlock }
     * 
     */
    public ElseBlock createElseBlock() {
        return new ElseBlock();
    }

    /**
     * Create an instance of {@link GroovyScript }
     * 
     */
    public GroovyScript createGroovyScript() {
        return new GroovyScript();
    }

    /**
     * Create an instance of {@link EventActivityParams }
     * 
     */
    public EventActivityParams createEventActivityParams() {
        return new EventActivityParams();
    }

    /**
     * Create an instance of {@link EventData }
     * 
     */
    public EventData createEventData() {
        return new EventData();
    }

    /**
     * Create an instance of {@link PropertiesMapping }
     * 
     */
    public PropertiesMapping createPropertiesMapping() {
        return new PropertiesMapping();
    }

    /**
     * Create an instance of {@link CamelRoute }
     * 
     */
    public CamelRoute createCamelRoute() {
        return new CamelRoute();
    }

    /**
     * Create an instance of {@link FeatureContext }
     * 
     */
    public FeatureContext createFeatureContext() {
        return new FeatureContext();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link ConditionSuccess }
     * 
     */
    public ConditionSuccess createConditionSuccess() {
        return new ConditionSuccess();
    }

    /**
     * Create an instance of {@link ConditionFaliure }
     * 
     */
    public ConditionFaliure createConditionFaliure() {
        return new ConditionFaliure();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link EmailNotification }
     * 
     */
    public EmailNotification createEmailNotification() {
        return new EmailNotification();
    }

    /**
     * Create an instance of {@link MailAttachments }
     * 
     */
    public MailAttachments createMailAttachments() {
        return new MailAttachments();
    }

    /**
     * Create an instance of {@link MailAttachment }
     * 
     */
    public MailAttachment createMailAttachment() {
        return new MailAttachment();
    }

    /**
     * Create an instance of {@link DBConfig }
     * 
     */
    public DBConfig createDBConfig() {
        return new DBConfig();
    }

    /**
     * Create an instance of {@link DbmsMapper }
     * 
     */
    public DbmsMapper createDbmsMapper() {
        return new DbmsMapper();
    }

    /**
     * Create an instance of {@link RowMapper }
     * 
     */
    public RowMapper createRowMapper() {
        return new RowMapper();
    }

    /**
     * Create an instance of {@link XmlFieldMapper }
     * 
     */
    public XmlFieldMapper createXmlFieldMapper() {
        return new XmlFieldMapper();
    }

    /**
     * Create an instance of {@link FieldMapper }
     * 
     */
    public FieldMapper createFieldMapper() {
        return new FieldMapper();
    }

    /**
     * Create an instance of {@link FtlpathMapper }
     * 
     */
    public FtlpathMapper createFtlpathMapper() {
        return new FtlpathMapper();
    }

    /**
     * Create an instance of {@link FtlDataMapper }
     * 
     */
    public FtlDataMapper createFtlDataMapper() {
        return new FtlDataMapper();
    }

    /**
     * Create an instance of {@link FtlfieldMapper }
     * 
     */
    public FtlfieldMapper createFtlfieldMapper() {
        return new FtlfieldMapper();
    }

    /**
     * Create an instance of {@link FtlPathMap }
     * 
     */
    public FtlPathMap createFtlPathMap() {
        return new FtlPathMap();
    }

    /**
     * Create an instance of {@link FtlMapto }
     * 
     */
    public FtlMapto createFtlMapto() {
        return new FtlMapto();
    }

    /**
     * Create an instance of {@link XsltpathMapper }
     * 
     */
    public XsltpathMapper createXsltpathMapper() {
        return new XsltpathMapper();
    }

    /**
     * Create an instance of {@link XsltPathMap }
     * 
     */
    public XsltPathMap createXsltPathMap() {
        return new XsltPathMap();
    }

}
