//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.19 at 05:01:20 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://attunedlabs.com/internal/integration-fwk-Supporting")
package com.attunedlabs.integrationfwk.config.jaxb;
