//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.19 at 05:34:04 PM IST 
//


package com.attunedlabs.feature.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GenericRestEndpoint" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="httpMethod" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="POST"/>
 *                       &lt;enumeration value="GET"/>
 *                       &lt;enumeration value="PUT"/>
 *                       &lt;enumeration value="DELETE"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="urlMappingScheme" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ConcreteSoapEndpoint" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="wsdl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="enabled" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="vendorName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "genericRestEndpoint",
    "concreteSoapEndpoint"
})
public class Service
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "GenericRestEndpoint")
    protected GenericRestEndpoint genericRestEndpoint;
    @XmlElement(name = "ConcreteSoapEndpoint")
    protected ConcreteSoapEndpoint concreteSoapEndpoint;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "enabled", required = true)
    protected boolean enabled;
    @XmlAttribute(name = "vendorName", required = true)
    protected String vendorName;
    @XmlAttribute(name = "Description", required = true)
    protected String description;

    /**
     * Gets the value of the genericRestEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link GenericRestEndpoint }
     *     
     */
    public GenericRestEndpoint getGenericRestEndpoint() {
        return genericRestEndpoint;
    }

    /**
     * Sets the value of the genericRestEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericRestEndpoint }
     *     
     */
    public void setGenericRestEndpoint(GenericRestEndpoint value) {
        this.genericRestEndpoint = value;
    }

    /**
     * Gets the value of the concreteSoapEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link ConcreteSoapEndpoint }
     *     
     */
    public ConcreteSoapEndpoint getConcreteSoapEndpoint() {
        return concreteSoapEndpoint;
    }

    /**
     * Sets the value of the concreteSoapEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConcreteSoapEndpoint }
     *     
     */
    public void setConcreteSoapEndpoint(ConcreteSoapEndpoint value) {
        this.concreteSoapEndpoint = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the vendorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * Sets the value of the vendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorName(String value) {
        this.vendorName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
